#https://www.rabbitmq.com/docs/vhosts
#https://www.rabbitmq.com/kubernetes/operator/using-topology-operator#vhosts
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: transactionrequest-vhost # name of this custom resource
  namespace: rabbitmq-bvt
spec:
  name: transactionrequest # name of vhost
  rabbitmqClusterReference:
    name: bvt-rabbitmqcluster